/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.alquilatucochefinal;

import static com.company.alquilatucochefinal.AlquilaTuCocheFINAL.coches;
import com.company.alquilatucochefinal.CocheFINAL.Tipo;
import com.company.alquilatucochefinal.dependency.Imagen;
import java.awt.Font;
import java.awt.Rectangle;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JComboBox;
import javax.swing.JViewport;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author ChiquitoS11
 */
public class GUIFINAL extends javax.swing.JFrame {

    ArrayList<CocheFINAL> cochesGUI = new ArrayList<>();

    String rutaFuente = "./SF-Pro.ttf";
    CocheFINAL cocheSeleccionado;

    Imagen imgFondo = new Imagen(getClass().getResource("/resources/cochesFONDO.gif"));
    Imagen btnCerrarIMG = new Imagen(getClass().getResource("/resources/btnCerrar.png"));
    Imagen btnMinimizarIMG = new Imagen(getClass().getResource("/resources/btnMinimizar.png"));
    Imagen btnAdminIMG = new Imagen(getClass().getResource("/resources/btnAdmin.png"));
    Imagen btnArrowLeft = new Imagen(getClass().getResource("/resources/arrow_left.png"));
    Imagen btnArrowRight = new Imagen(getClass().getResource("/resources/arrow_right.png"));
    
    public GUIFINAL() {
        this.setContentPane(imgFondo);
        
        initComponents();

        cargarArrayList();
        almacenarDatosObjeto();
        ajustesVisuales();
        
        // hago uso del Thread despues de cargar los componentes y metodos necesarios para evitar errores
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                // Método que se ejecutará en paralelo
                while (true) { 
                    try {
                        cambiarImagen();
                        // El tiempo de carga entre imagenes
                        Thread.sleep(1500);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        
        thread.start();
    }
    
    int contador = 0;
    public void cambiarImagen() {
        if (opcionAtributo == 0) {
            int numero = (int) (Math.random() * (fotosIMG.size()-1)) + 1;
            
            
            if (contador != fotosIMG.size()) {
                
                System.out.println("cambio: " + contador);
                cocheIMGLABEL.setIcon((fotosIMG.get(numero)).imgToCOMPONENT(cocheIMGLABEL));   
            } else {
                contador = 0;
            }  
            contador += 1;
            
        } else {
            contador = 0;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrarLabel = new javax.swing.JLabel();
        btnMinimizarLabel = new javax.swing.JLabel();
        btnAdminLabel = new javax.swing.JLabel();
        adminOrUserPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        resultadosCB = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cocheIMGLABEL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);

        btnCerrarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarLabelMouseExited(evt);
            }
        });

        btnMinimizarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinimizarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnAdminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminLabelMouseExited(evt);
            }
        });

        adminOrUserPanel.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Busqueda:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Restultados:");

        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        resultadosCB.setToolTipText("");
        resultadosCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosCBActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setFocusable(false);
        jLabel3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel3MouseWheelMoved(evt);
            }
        });
        jScrollPane3.setViewportView(jLabel3);

        jPanel2.setOpaque(false);

        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cocheIMGLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(cocheIMGLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout adminOrUserPanelLayout = new javax.swing.GroupLayout(adminOrUserPanel);
        adminOrUserPanel.setLayout(adminOrUserPanelLayout);
        adminOrUserPanelLayout.setHorizontalGroup(
            adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminOrUserPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminOrUserPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminOrUserPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultadosCB, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(457, Short.MAX_VALUE))
        );
        adminOrUserPanelLayout.setVerticalGroup(
            adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminOrUserPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminOrUserPanelLayout.createSequentialGroup()
                        .addGroup(adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(adminOrUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultadosCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(Solo se puede alquilar un coche");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("de la ''Busqueda' MODELO)");

        jButton4.setText("ALQUILAR");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(adminOrUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(539, 539, 539)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminOrUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarLabelMouseClicked
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCerrarLabelMouseClicked

    private void btnMinimizarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarLabelMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarLabelMouseClicked

    private void btnCerrarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarLabelMouseEntered
        btnCerrarLabel.setIcon(btnCerrarIMG.cambiarOpacidad(0.5f, btnCerrarLabel));
    }//GEN-LAST:event_btnCerrarLabelMouseEntered

    private void btnCerrarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarLabelMouseExited
        btnCerrarLabel.setIcon(btnCerrarIMG.imgToCOMPONENT(btnCerrarLabel));
    }//GEN-LAST:event_btnCerrarLabelMouseExited

    private void btnMinimizarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarLabelMouseEntered
        btnMinimizarLabel.setIcon(btnMinimizarIMG.cambiarOpacidad(0.5f, btnMinimizarLabel));
    }//GEN-LAST:event_btnMinimizarLabelMouseEntered

    private void btnMinimizarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarLabelMouseExited
        btnMinimizarLabel.setIcon(btnMinimizarIMG.imgToCOMPONENT(btnMinimizarLabel));
    }//GEN-LAST:event_btnMinimizarLabelMouseExited

    private void btnAdminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLabelMouseClicked

    }//GEN-LAST:event_btnAdminLabelMouseClicked

    private void btnAdminLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLabelMouseEntered
        btnAdminLabel.setIcon(btnAdminIMG.cambiarOpacidad(0.5f, btnAdminLabel));
    }//GEN-LAST:event_btnAdminLabelMouseEntered

    private void btnAdminLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLabelMouseExited
        btnAdminLabel.setIcon(btnAdminIMG.imgToCOMPONENT(btnAdminLabel));
    }//GEN-LAST:event_btnAdminLabelMouseExited

    
    static int opcionAtributo;
    /**
     * Si se ha agregado nuevos atributos a la clase
     * ...<P>
     * Por favor actualizar esta funcion, ya que
     * <P>
     * regula la aparicion de los atributos de clase (tampoco olvide actualizar
     * el toString)
     *
     * @param evt
     */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        opcionAtributo = jComboBox1.getSelectedIndex();

        switch (opcionAtributo) {
            case 0:
                System.out.println("Mostrar Todo");
                jLabel2.setVisible(false);
                resultadosCB.setVisible(false);

                adminOrUserPanel.revalidate();
                adminOrUserPanel.repaint();
                break;

            case 1:
                System.out.println("Marca");
                jLabel2.setVisible(true);
                resultadosCB.setVisible(true);
                resultadosCB.removeAllItems();

                for (CocheFINAL c : cochesGUI) {
                    if (c.disponibilidad == true) {
                        resultadosCB.addItem(c.marca);
                    }
                    
                }
                eliminarElementosDuplicados(resultadosCB);

                adminOrUserPanel.revalidate();
                adminOrUserPanel.repaint();
                break;

            case 2:
                System.out.println("Modelo");
                jLabel2.setVisible(true);
                resultadosCB.setVisible(true);
                resultadosCB.removeAllItems();

                for (CocheFINAL c : cochesGUI) {
                    if (c.disponibilidad == true) {
                        resultadosCB.addItem(c.modelo);
                    }
                }
                eliminarElementosDuplicados(resultadosCB);

                adminOrUserPanel.revalidate();
                adminOrUserPanel.repaint();
                break;

            case 3:
                System.out.println("Numero de plazas");
                jLabel2.setVisible(true);
                resultadosCB.setVisible(true);
                resultadosCB.removeAllItems();

                for (CocheFINAL c : cochesGUI) {
                    if (c.disponibilidad == true) {
                    resultadosCB.addItem(String.valueOf(c.numeroPlazas));
                    }
                }
                eliminarElementosDuplicados(resultadosCB);

                adminOrUserPanel.revalidate();
                adminOrUserPanel.repaint();
                break;

            case 4:
                System.out.println("Tipo");
                jLabel2.setVisible(true);
                resultadosCB.setVisible(true);
                resultadosCB.removeAllItems();

                for (CocheFINAL c : cochesGUI) {
                    if (c.disponibilidad == true) {
                        resultadosCB.addItem(c.tipo.toString());
                    }
                }
                eliminarElementosDuplicados(resultadosCB);

                adminOrUserPanel.revalidate();
                adminOrUserPanel.repaint();
                break;

            case 5:
                System.out.println("Precio Alquiler Diario");
                jLabel2.setVisible(true);
                resultadosCB.setVisible(true);
                resultadosCB.removeAllItems();

                for (CocheFINAL c : cochesGUI) {
                    if (c.disponibilidad == true) {
                        resultadosCB.addItem(String.valueOf(c.alquilerDia));
                    }
                }
                
                eliminarElementosDuplicados(resultadosCB);

                adminOrUserPanel.revalidate();
                adminOrUserPanel.repaint();
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
   
    
    static String txt = "";
    private void resultadosCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosCBActionPerformed
        jButton4.setEnabled(false);
        
        String opcion = (String) resultadosCB.getSelectedItem();
        int opcionNumero = 0;
        double opcionNumer = 0;

        
        // por alguna extraña razon si cambias el orden de opcionNumer debajo de opcionNumero la 'caja' donde se almacenan los precios explota y todo deja de funcionar xd
        // presiento que es porque da una excepcion el integer antes que el double y por eso se sale sin antes controlar la excepcion del double
        // pero cuando manejas la excepcion del double esto no pasa, ademas de que no funciona controlar la excepcion de NumberFormatException, da una otra extraña y no me quedo
        // otra solución que controlarlas todas ante posibles fallos, si estas leyendo esto espero que logres descubrir el misterio de este try...
        // MANERA 1 de arreglar el double
        try { 
            opcionNumer = Double.parseDouble(opcion);
            opcionNumero = Integer.parseInt(opcion);
        }
        catch (Exception ex){
//            ex.printStackTrace();
        }
    
        //MANERA 2 de arreglar el double
//        if (opcionAtributo == 5) {
//            try {
//                System.out.println("opcion vale");
//                System.out.println(opcion);
//                opcionNumer = Double.parseDouble(opcion);
//            }
//            catch (Exception ex){
////                ex.printStackTrace();
//            }
//        }
        
        for (CocheFINAL c : cochesGUI) {
            
            if (opcionAtributo == 1 && c.getMarca().equals(opcion) && c.disponibilidad == true) {
                
                cocheIMGLABEL.setIcon((c.getFotoIMAGEN_ARRAY().get(0)).imgToCOMPONENT(cocheIMGLABEL));
                txt += c.toString() + "\n";
            }
            if (opcionAtributo == 2 && (c.getModelo().equals(opcion)) && c.disponibilidad == true) {
                jButton4.setEnabled(true);
                cocheIMGLABEL.setIcon((c.getFotoIMAGEN_ARRAY().get(0)).imgToCOMPONENT(cocheIMGLABEL));
                txt += c.toString() + "\n";
            }
            if (opcionAtributo == 3 && (c.getNumeroPlazas() == opcionNumero) && c.disponibilidad == true) {
                
                cocheIMGLABEL.setIcon((c.getFotoIMAGEN_ARRAY().get(0)).imgToCOMPONENT(cocheIMGLABEL));
                txt += c.toString() + "\n";
            }
            if (opcionAtributo == 4 && (c.getTipo().toString().equals(opcion)) && c.disponibilidad == true) {
                
                cocheIMGLABEL.setIcon((c.getFotoIMAGEN_ARRAY().get(0)).imgToCOMPONENT(cocheIMGLABEL));
                txt += c.toString() + "\n";
            }
            if (opcionAtributo == 5 && (c.getAlquilerDia() == opcionNumer) && c.disponibilidad == true) {
                        
                cocheIMGLABEL.setIcon((c.getFotoIMAGEN_ARRAY().get(0)).imgToCOMPONENT(cocheIMGLABEL));
                txt += c.toString() + "\n";
            } 
        }

        jLabel3.setText(txt + "</html>"); // poder crear un salto de linea con el formato HTML
        txt = ""; // formatea la variable txt, para que no se acumulen los coches
    }//GEN-LAST:event_resultadosCBActionPerformed
    
    /**
     * Este metodo tiene su miga y se encarga de reorganizar la barra de desplazamiento {@code (scroll)} <P>
     * 
     * @param evt 
     */
    private void jLabel3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel3MouseWheelMoved
        
        JViewport viewport = jScrollPane3.getViewport();
        Rectangle viewRect = viewport.getViewRect();
                
        int scrollAmount = evt.getUnitsToScroll() * 20; // cambiar velocidad del scroll
 
        // sepaCristo...
        viewRect.y += scrollAmount;
        viewRect.y = Math.max(0, Math.min(viewRect.y, viewport.getViewSize().height - viewRect.height));
        viewport.setViewPosition(viewRect.getLocation());

    }//GEN-LAST:event_jLabel3MouseWheelMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Alquilar alq = new Alquilar(this);
        alq.setVisible(true);
        alq.setLocationRelativeTo(null);
        alq.setResizable(false);
        alq.setSize(320, 250);
    }//GEN-LAST:event_jButton4ActionPerformed

    
    public void cargarArrayList() {
        
        for (CocheFINAL c : coches) {
            (this.cochesGUI).add(c);
//            System.out.println("asd");
        }
        
    }

    /**
     * Los HashSet eliminan automaticamente los elementos repetidos
     * <P>
     * este metodo borra todos los elementos repetidos
     * <P>
     * Dejando su aparicion una unica vez por elemento.
     *
     * @param comboBox
     */
    public void eliminarElementosDuplicados(JComboBox<String> comboBox) {
        HashSet<String> elementosUnicos = new HashSet<>();

        for (int i = 0; i < comboBox.getItemCount(); i++) {
            elementosUnicos.add(comboBox.getItemAt(i));
        }
        comboBox.removeAllItems();

        elementosUnicos.forEach(comboBox::addItem);
    }

    /**
     * Configuracion visuales necesarias :p
     */
    public void ajustesVisuales() {
        
        // botones para cambiar la foto de la GUI
        jButton1.setIcon(btnArrowLeft.imgToCOMPONENT(jButton1)); 
        jButton1.setFocusPainted(false);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
    
        jButton2.setIcon(btnArrowRight.imgToCOMPONENT(jButton2));
        jButton2.setFocusPainted(false);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        
        
        // Desactivamos las barras de desplazamiento
        jScrollPane3.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.getViewport().setOpaque(false);
        jScrollPane3.setOpaque(false);
        
        // imagenes
        btnAdminLabel.setIcon(btnAdminIMG.imgToCOMPONENT(btnAdminLabel));
        btnCerrarLabel.setIcon(btnCerrarIMG.imgToCOMPONENT(btnCerrarLabel));
        btnMinimizarLabel.setIcon(btnMinimizarIMG.imgToCOMPONENT(btnMinimizarLabel));

        // fuentes
        jLabel1.setFont(cargarFuente(16));
        jLabel2.setFont(cargarFuente(16));
        jLabel3.setFont(cargarFuente(14));
        jComboBox1.setFont(cargarFuente(16));
        resultadosCB.setFont(cargarFuente(16));
        jLabel5.setFont(cargarFuente(16));
        jLabel6.setFont(cargarFuente(16));
        jButton4.setFont(cargarFuente(16));

        // boton de Busqueda
        jComboBox1.addItem("Mostar Todo");
        jComboBox1.addItem("Marca");
        jComboBox1.addItem("Modelo");
        jComboBox1.addItem("Numero de Plazas");
        jComboBox1.addItem("Tipo");
        jComboBox1.addItem("Precio Alquiler Diario");
    }

    static ArrayList<String> marca = new ArrayList<>();
    static ArrayList<String> modelo = new ArrayList<>();
    static ArrayList<Integer> nPlazas = new ArrayList<>();
    
    static ArrayList<Tipo> tipo = new ArrayList<>();
    
    static ArrayList<Double> pDiario = new ArrayList<>();
    static ArrayList<Imagen> fotosIMG = new ArrayList<>();
    
    
    /**
     * Almacena todos los datos de la clase CocheFINAL <P>
     * dentro de arrayLista para posterior uso
     */
    public void almacenarDatosObjeto() {

        for (CocheFINAL c : coches) {
            marca.add(c.getMarca());
        }

        for (CocheFINAL c : coches) {
            modelo.add(c.getMarca());
        }

        for (CocheFINAL c : coches) {
            nPlazas.add(c.getNumeroPlazas());
        }

        for (CocheFINAL c : coches) {
            tipo.add(c.getTipo());
        }

        for (CocheFINAL c : coches) {
            pDiario.add(c.getAlquilerDia());
        }
        
        for (CocheFINAL c : coches) {
            for (int i = 0; i < c.getFotoIMAGEN_ARRAY().size(); i++) {
               fotosIMG.add(c.getFotoIMAGEN_ARRAY().get(i)); 
            }
                    
        }    
    }

    /**
     * carga la fuente para su posterior uso en cada componente
     *
     * @param fontSize tamanio en int de la fuente
     * @return
     */
    public Font cargarFuente(int fontSize) {
        try {
            // Cargar la fuente desde el archivo externo
            return Font.createFont(Font.TRUETYPE_FONT, new File(rutaFuente)).deriveFont(Font.PLAIN, fontSize);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void cargarDetallesCoche() {
//        jTextArea1.append();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminOrUserPanel;
    private javax.swing.JLabel btnAdminLabel;
    private javax.swing.JLabel btnCerrarLabel;
    private javax.swing.JLabel btnMinimizarLabel;
    private javax.swing.JLabel cocheIMGLABEL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JComboBox<String> resultadosCB;
    // End of variables declaration//GEN-END:variables
}
